name: E2E Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      APP_URL: https://stage-app.stakewise.io
      API_URL: https://stage-api.stakewise.io
      GNOSIS_RPC_URL: https://rpc.gnosischain.com
      MAINNET_RPC_URL: https://mainnet.infura.io/v3/84842078b09946638c03157f83405213
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: xvfb-run --auto-servernum npm run e2e
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7
